### ISSUE TITLE
Example pes/neb fails to launch

### ISSUE THREAD

**Issue by pjuda** [cosmo-epfl/i-pi-dev#213]
Example in examples/pes/neb exits with the following error:

```
Traceback (most recent call last):
  File "/home/pjuda/bin/i-pi", line 101, in <module>
    main(args[0], options.do_yappi)
  File "/home/pjuda/bin/i-pi", line 48, in main
    simulation = Simulation.load_from_xml(fn_input, request_banner=True)
  File "/home/pjuda/source/i-pi-dev/ipi/engine/simulation.py", line 88, in load_from_xml
    simulation = input_simulation.fetch()
  File "/home/pjuda/source/i-pi-dev/ipi/inputs/simulation.py", line 181, in fetch
    syslist.append(v.fetch())
  File "/home/pjuda/source/i-pi-dev/ipi/inputs/system.py", line 129, in fetch
    motion = self.motion.fetch(),
  File "/home/pjuda/source/i-pi-dev/ipi/inputs/motion/motion.py", line 178, in fetch
    motion=super(InputMotion,self).fetch()
  File "/home/pjuda/source/i-pi-dev/ipi/inputs/motion/motion.py", line 136, in fetch
    sc = NEBMover(fixcom=self.fixcom.fetch(), fixatoms=self.fixatoms.fetch(), **self.neb_optimizer.fetch())
TypeError: __init__() got an unexpected keyword argument 'scale_lbfgs' 
```

**Comment by bhelfrecht** [comment]
I'm working on this. I believe I have the issue solved, but give me a few days to verify and finalize.
