### ISSUE TITLE
lammps/h2o-alchemical example does not work

### ISSUE THREAD

**Issue by pjuda** [cosmo-epfl/i-pi-dev#219]
The example `lammps/h2o-alchemical` does not work.

To reproduce, go to `examples/lammps` and use 
`make h2o-alchemical`

This will give the following i-PI error:
```
Traceback (most recent call last):
  File "/home/pjuda/bin/i-pi", line 101, in <module>
    main(args[0], options.do_yappi)
  File "/home/pjuda/bin/i-pi", line 51, in main
    simulation.run()
  File "/home/pjuda/source/i-pi-dev/ipi/engine/simulation.py", line 275, in run
    s.motion.step(step=self.step)
  File "/home/pjuda/source/i-pi-dev/ipi/engine/motion/multi.py", line 49, in step
    m.step(step)
  File "/home/pjuda/source/i-pi-dev/ipi/engine/motion/alchemy.py", line 97, in step
    wk2 = dstrip(self.nm.omegak2)
  File "/home/pjuda/source/i-pi-dev/ipi/utils/depend.py", line 749, in __getattribute__
    value = super(dobject, self).__getattribute__(name)
AttributeError: 'NormalModes' object has no attribute 'omegak2'
```

**Comment by ceriottm** [comment]
Fixed.
